### ISSUE TITLE
Handle --drop when users are connected

### ISSUE THREAD

**Issue by jessetechie** [jeffdoolittle/DbTransmogrifier#9]
This scenario is for postgres but may also apply to SQL server.

When --drop is called but users are connected, the application generates an unhandled exception.

There are a couple ways this could be better:
* Handle the exception and tell the user what to do
* Have a separate option (```--disconnect-all-users``` perhaps) that runs the below query ([source](http://www.postgresqltutorial.com/postgresql-drop-database/))

```
SELECT
	pg_terminate_backend (pg_stat_activity.pid)
FROM
	pg_stat_activity
WHERE
	pg_stat_activity.datname = 'target_database';
```

(Note: ```pg_stat_activity.pid``` is for 9.2 and up; it's ```procid``` prior to that)

**Comment by jeffdoolittle** [comment]
I vote we don't worry about 9.2 and prior.
